# Generated by Django 3.2.7 on 2021-09-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('age', models.IntegerField(default=0)),
                ('name', models.CharField(default='null', max_length=32)),
                ('email', models.CharField(default='null', max_length=32)),
                ('birthday', models.DateField(default='1901-01-01')),
            ],
        ),
    ]
