# Generated by Django 3.2.8 on 2021-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(default='null', max_length=32)),
                ('last_name', models.CharField(default='null', max_length=32)),
                ('company', models.CharField(default='null', max_length=32)),
                ('email', models.CharField(default='null', max_length=32)),
                ('phone', models.CharField(default='null', max_length=32)),
                ('mobile', models.CharField(default='null', max_length=32)),
                ('address', models.CharField(default='null', max_length=512)),
                ('birthday', models.DateField(default='1901-01-01')),
                ('relationship', models.CharField(default='null', max_length=32)),
                ('notes', models.CharField(default='null', max_length=256)),
                ('image_address', models.CharField(default='null', max_length=256)),
            ],
        ),
    ]
