# Generated by Django 3.2.8 on 2021-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('location', models.CharField(default='null', max_length=256)),
                ('date', models.DateField(default='1901-01-01')),
                ('content', models.CharField(default='null', max_length=256)),
            ],
        ),
    ]
