# Account Operations
ACCOUNT_LOGIN_SUCCESS = 100
ACCOUNT_LOGIN_FAIL = 101
ACCOUNT_REGISTER_SUCCESS = 105
ACCOUNT_REGISTER_FAIL = 106
ACCOUNT_UPDATE_SUCCESS = 110
ACCOUNT_UPDATE_FAIL = 111
ACCOUNT_LOGOUT_SUCCESS = 115
ACCOUNT_TOKEN_ERROR = 120

# Contact Operations
CONTACT_ADD_SUCCESS = 200
CONTACT_ADD_FAIL = 201
CONTACT_DELETE_SUCCESS = 205
CONTACT_UPDATE_SUCCESS = 210
CONTACT_UPDATE_FAIL = 211
CONTACT_GET_ALL_SUCCESS = 215
CONTACT_GET_SUCCESS = 220


